name: Tests 
on:
  pull_request:
    branches:
      - "*"
jobs:
  test-jest:
    name: Jest
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install
      - name: Tests
        run: yarn run test-jest
